# PACKAGE-OWNED — scaffold writes this once and never overwrites it.
# The docs navigation tree. Add tutorial / guide pages here as the package
# grows; `make.jl` reads `pages` from this file. The API reference and the
# README-derived home page are generated by `make.jl`.
#
# The Benchmarks entry below is written only when the package is scaffolded with
# `benchmarks = true` (it is the `` substitution); a package
# without benchmarks gets no entry and no page.

pages = [
    "Home" => "index.md",
    # Authored quickstart (package-owned source pages, distinct from the
    # README-derived home page). Add tutorials under `getting-started/` as the
    # package grows.
    "Getting started" => [
        "Overview" => "getting-started/index.md",
        "Lowering" => [
            "Lowering a distribution to a dynamical system" => "getting-started/tutorials/lowering-backends.md",
            "SciMLBase: the ODE view" => "getting-started/tutorials/backend-sciml.md",
            "Catalyst: reaction networks" => "getting-started/tutorials/backend-catalyst.md",
            "JumpProcesses: stochastic simulation" => "getting-started/tutorials/backend-jump.md",
            "AlgebraicPetri: Petri nets" => "getting-started/tutorials/backend-petri.md",
            "Composing delays: convolution" => "getting-started/tutorials/composing-delays.md"
        ],
        "Fitting under AD (Turing)" => "getting-started/tutorials/fitting-ad-stable.md"
    ],
    "API reference" => [
        "Public API" => "lib/public.md",
        "Internal API" => "lib/internals.md"
    ]
]
