# PACKAGE-OWNED — scaffold writes this once and never overwrites it.
# The docs navigation tree. Add tutorial / guide pages here as the package
# grows; `make.jl` reads `pages` from this file. The API reference and the
# README-derived home page are generated by `make.jl`.
#
# The Benchmarks entry below is written only when the package is scaffolded with
# `benchmarks = true` (it is the `` substitution); a package
# without benchmarks gets no entry and no page.

pages = [
    "Home" => "index.md",
    # Authored quickstart (package-owned source pages, distinct from the
    # README-derived home page). Add tutorials under `getting-started/` as the
    # package grows.
    "Getting started" => [
        "Overview" => "getting-started/index.md",
        "Lowering a distribution to a dynamical system" => "getting-started/tutorials/lowering-backends.md",
        "Customising your docs" => "getting-started/customising.md"
    ],
    "API reference" => [
        "Public API" => "lib/public.md",
        "Internal API" => "lib/internals.md"
    ],
    # Maintainer-facing reference: how the kit's managed infrastructure and
    # template sync keep this repository to the shared standard. Kept out of
    # Getting started so a new user's first section is not maintainer noise.
    "Development" => [
        "Infrastructure and template sync" => "getting-started/infrastructure.md"
    ]
]
